GET http://localhost:3000/users

### register

POST /register HTTP/1.1
Host: localhost:4000
Content-Type: application/json

{
    "name": "Kylo",
    "email": "test@test.com",
    "password": "password"
}

### login
POST /login HTTP/1.1
Host: localhost:4000
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}

###

GET http://localhost:3000/users/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsbyIsImlhdCI6MTYxMDk5ODQwNCwiZXhwIjoxNjEwOTk4NDE5fQ.w11O7tBw7-CxrfkYI4PxJr11dwF7gK91BV09Wbrq5IQ

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsbyIsImlhdCI6MTYxMDk5ODQwNCwiZXhwIjoxNjEwOTk4NDE5fQ.w11O7tBw7-CxrfkYI4PxJr11dwF7gK91BV09Wbrq5IQ"
}