GET http://localhost:3000/user/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJuYW1lIjoiS3lsbyIsImlhdCI6MTYxMTI3NTk2OSwiZXhwIjoyMjU5Mjc1OTY5fQ.ACESLWSHN0Syt7GttRXf0KvytYfWRvUpdC_tSp4ewus

###

PATCH http://localhost:3000/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJuYW1lIjoiS3lsbyIsImlhdCI6MTYxMTI3NTk2OSwiZXhwIjoyMjU5Mjc1OTY5fQ.ACESLWSHN0Syt7GttRXf0KvytYfWRvUpdC_tSp4ewus

### register

POST /register HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "username": "Kylo",
    "email": "kylo@test.com",
    "password": "password"
}

### login
POST /login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "email": "kylo@test.com",
    "password": "password"
}

###

GET http://localhost:3000/users/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJuYW1lIjoiS3lsbyIsImlhdCI6MTYxMTI3NTk2OSwiZXhwIjoyMjU5Mjc1OTY5fQ.ACESLWSHN0Syt7GttRXf0KvytYfWRvUpdC_tSp4ewus

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsbyIsImlhdCI6MTYxMDk5ODk5MX0.mUJFqsCLnqUxBdoX3paDES4bgdArnQqrVtc9pN86EbE"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTEwMDg1NjJ9.f9UKe7bqiAgyJb9lvdkfCGU-BqN1Aualy5Hlu5AL8VQ"
}

###

GET http://localhost:3000/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJuYW1lIjoiS3lsbyIsImlhdCI6MTYxMTI3NTk2OSwiZXhwIjoyMjU5Mjc1OTY5fQ.ACESLWSHN0Syt7GttRXf0KvytYfWRvUpdC_tSp4ewus
###

GET http://localhost:3000/rooms/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJuYW1lIjoiS3lsbyIsImlhdCI6MTYxMTI3NTk2OSwiZXhwIjoyMjU5Mjc1OTY5fQ.ACESLWSHN0Syt7GttRXf0KvytYfWRvUpdC_tSp4ewus

###

POST http://localhost:3000/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJuYW1lIjoiS3lsbyIsImlhdCI6MTYxMTI3NTk2OSwiZXhwIjoyMjU5Mjc1OTY5fQ.ACESLWSHN0Syt7GttRXf0KvytYfWRvUpdC_tSp4ewus
Content-Type: application/json

{
    "name": "testRoom"
}

###

GET http://localhost:3000/rooms/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJuYW1lIjoiS3lsbyIsImlhdCI6MTYxMTI3NTk2OSwiZXhwIjoyMjU5Mjc1OTY5fQ.ACESLWSHN0Syt7GttRXf0KvytYfWRvUpdC_tSp4ewus

###